use_frameworks!

target 'DCColor_Example' do
  pod 'DCColor', :path => '../'
  pod 'DCCoreGraphics', :path => '~/Developer/sharedCode/Modules/DCCoreGraphics'
  
  target 'DCColor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
